// app/layout.js
import '../styles/globals.css'; // ✅ importa qui i tuoi stili globali

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
